package com.android.styy.common.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.styy.common.dao.TokenEntity;
import com.android.styy.common.dao.UserEntity;

import com.android.styy.common.dao.TokenEntityDao;
import com.android.styy.common.dao.UserEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tokenEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;

    private final TokenEntityDao tokenEntityDao;
    private final UserEntityDao userEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tokenEntityDaoConfig = daoConfigMap.get(TokenEntityDao.class).clone();
        tokenEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        tokenEntityDao = new TokenEntityDao(tokenEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);

        registerDao(TokenEntity.class, tokenEntityDao);
        registerDao(UserEntity.class, userEntityDao);
    }
    
    public void clear() {
        tokenEntityDaoConfig.clearIdentityScope();
        userEntityDaoConfig.clearIdentityScope();
    }

    public TokenEntityDao getTokenEntityDao() {
        return tokenEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

}
